# Generated by Django 3.2.19 on 2024-04-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempstorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempstorage',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
